var annotated =
[
    [ "Steinberg", null, [
      [ "FUnknownImpl", null, null ],
      [ "Vst", null, [
        [ "LegacyMIDICCOut", "namespaceSteinberg_1_1Vst_1_1LegacyMIDICCOut.html", "namespaceSteinberg_1_1Vst_1_1LegacyMIDICCOut" ],
        [ "mda", "namespaceSteinberg_1_1Vst_1_1mda.html", "namespaceSteinberg_1_1Vst_1_1mda" ],
        [ "NoteExpressionSynth", "namespaceSteinberg_1_1Vst_1_1NoteExpressionSynth.html", "namespaceSteinberg_1_1Vst_1_1NoteExpressionSynth" ],
        [ "AudioHost", "namespaceSteinberg_1_1Vst_1_1AudioHost.html", "namespaceSteinberg_1_1Vst_1_1AudioHost" ],
        [ "EditorHost", "namespaceSteinberg_1_1Vst_1_1EditorHost.html", "namespaceSteinberg_1_1Vst_1_1EditorHost" ],
        [ "IDelayTestController", "classSteinberg_1_1Vst_1_1IDelayTestController.html", "classSteinberg_1_1Vst_1_1IDelayTestController" ],
        [ "ADelayController", "classSteinberg_1_1Vst_1_1ADelayController.html", "classSteinberg_1_1Vst_1_1ADelayController" ],
        [ "ADelayProcessor", "classSteinberg_1_1Vst_1_1ADelayProcessor.html", "classSteinberg_1_1Vst_1_1ADelayProcessor" ],
        [ "AGain", "classSteinberg_1_1Vst_1_1AGain.html", "classSteinberg_1_1Vst_1_1AGain" ],
        [ "AGainController", "classSteinberg_1_1Vst_1_1AGainController.html", "classSteinberg_1_1Vst_1_1AGainController" ],
        [ "AGainWithSideChain", "classSteinberg_1_1Vst_1_1AGainWithSideChain.html", "classSteinberg_1_1Vst_1_1AGainWithSideChain" ],
        [ "AGainUIMessageController", "classSteinberg_1_1Vst_1_1AGainUIMessageController.html", "classSteinberg_1_1Vst_1_1AGainUIMessageController" ],
        [ "Plug", "classSteinberg_1_1Vst_1_1Plug.html", "classSteinberg_1_1Vst_1_1Plug" ],
        [ "PlugController", "classSteinberg_1_1Vst_1_1PlugController.html", "classSteinberg_1_1Vst_1_1PlugController" ],
        [ "LogScale", "classSteinberg_1_1Vst_1_1LogScale.html", "classSteinberg_1_1Vst_1_1LogScale" ],
        [ "LogScaleParameter", "classSteinberg_1_1Vst_1_1LogScaleParameter.html", "classSteinberg_1_1Vst_1_1LogScaleParameter" ],
        [ "VoiceBase", "classSteinberg_1_1Vst_1_1VoiceBase.html", "classSteinberg_1_1Vst_1_1VoiceBase" ],
        [ "VoiceProcessor", "classSteinberg_1_1Vst_1_1VoiceProcessor.html", "classSteinberg_1_1Vst_1_1VoiceProcessor" ],
        [ "VoiceProcessorImplementation", "classSteinberg_1_1Vst_1_1VoiceProcessorImplementation.html", "classSteinberg_1_1Vst_1_1VoiceProcessorImplementation" ],
        [ "EditorSizeController", "classSteinberg_1_1Vst_1_1EditorSizeController.html", "classSteinberg_1_1Vst_1_1EditorSizeController" ],
        [ "HostCheckerController", "classSteinberg_1_1Vst_1_1HostCheckerController.html", "classSteinberg_1_1Vst_1_1HostCheckerController" ],
        [ "HostCheckerProcessor", "classSteinberg_1_1Vst_1_1HostCheckerProcessor.html", "classSteinberg_1_1Vst_1_1HostCheckerProcessor" ],
        [ "PitchNamesController", "classSteinberg_1_1Vst_1_1PitchNamesController.html", "classSteinberg_1_1Vst_1_1PitchNamesController" ],
        [ "PitchNamesProcessor", "classSteinberg_1_1Vst_1_1PitchNamesProcessor.html", "classSteinberg_1_1Vst_1_1PitchNamesProcessor" ],
        [ "SyncEntry", "structSteinberg_1_1Vst_1_1SyncEntry.html", "structSteinberg_1_1Vst_1_1SyncEntry" ],
        [ "SyncDelayController", "classSteinberg_1_1Vst_1_1SyncDelayController.html", "classSteinberg_1_1Vst_1_1SyncDelayController" ],
        [ "SyncDelayProcessor", "classSteinberg_1_1Vst_1_1SyncDelayProcessor.html", "classSteinberg_1_1Vst_1_1SyncDelayProcessor" ],
        [ "TestSuite", "classSteinberg_1_1Vst_1_1TestSuite.html", "classSteinberg_1_1Vst_1_1TestSuite" ],
        [ "Validator", "classSteinberg_1_1Vst_1_1Validator.html", "classSteinberg_1_1Vst_1_1Validator" ],
        [ "VstModule", "classSteinberg_1_1Vst_1_1VstModule.html", "classSteinberg_1_1Vst_1_1VstModule" ]
      ] ],
      [ "HostChecker", "namespaceSteinberg_1_1HostChecker.html", null ],
      [ "Panner", "namespaceSteinberg_1_1Panner.html", null ]
    ] ],
    [ "VST3", null, null ],
    [ "VSTGUI", null, [
      [ "EventLogDataBrowserSource", "classVSTGUI_1_1EventLogDataBrowserSource.html", "classVSTGUI_1_1EventLogDataBrowserSource" ],
      [ "NoteTouchController", "classVSTGUI_1_1NoteTouchController.html", "classVSTGUI_1_1NoteTouchController" ],
      [ "PitchNamesDataBrowserSource", "classVSTGUI_1_1PitchNamesDataBrowserSource.html", "classVSTGUI_1_1PitchNamesDataBrowserSource" ]
    ] ],
    [ "AGainUIMessageController", "classAGainUIMessageController.html", null ],
    [ "EventListCheck", "classEventListCheck.html", "classEventListCheck" ],
    [ "EventLogger", "classEventLogger.html", "classEventLogger" ],
    [ "HostCheck", "classHostCheck.html", "classHostCheck" ],
    [ "LogEvent", "structLogEvent.html", "structLogEvent" ],
    [ "ParameterChangesCheck", "classParameterChangesCheck.html", "classParameterChangesCheck" ],
    [ "ProcessContextCheck", "classProcessContextCheck.html", "classProcessContextCheck" ],
    [ "ProcessSetupCheck", "classProcessSetupCheck.html", "classProcessSetupCheck" ],
    [ "VSTInterAppAudioAppDelegate", "interfaceVSTInterAppAudioAppDelegate.html", null ],
    [ "VSTInterAppAudioHostUIControllerViewController", "interfaceVSTInterAppAudioHostUIControllerViewController.html", "interfaceVSTInterAppAudioHostUIControllerViewController" ]
];